name: CI

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: install quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render project to latex
        run: | 
          quarto render --to latex
          git add -f _book
          git commit -m "render original"
          OLD=$(git rev-parse HEAD)
          echo $OLD
      
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
