name: git-latexdiff
on:
  workflow_dispatch
permissions:
  contents: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: install quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: set up GitHub
        run: |
          git config --global user.name 'Nils'
          git config --global user.email 'ratnanil@users.noreply.github.com'

      - name: Render project to latex
        run: | 
          quarto render --to latex
          git add -f _book
          git commit -m "render original"
          OLD=$(git rev-parse HEAD)
      - name: Checkout Pull request and recompile to latex
        run: |
          git fetch origin pull/1/head:new-pr 
          git merge new-pr -m "merge pull request"
          quarto render --to latex
          git add -f _book
          git commit -m "render new"
          echo $OLD

