name: git-latexdiff
on:
  workflow_dispatch
permissions:
  contents: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: install quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: set up GitHub
        run: |
          git config --global user.name 'Nils'
          git config --global user.email 'ratnanil@users.noreply.github.com'

      - name: Render project to latex
        run: | 
          quarto render --to latex
          git add -f _book
          git commit -m "render original"
      - name: install latex-diff
        run: |
          git clone https://gitlab.com/git-latexdiff/git-latexdiff
          cd git-latexdiff
          sudo make install-bin
          cd ..
      - name: Checkout Pull request and recompile to latex
        run: |
          git fetch origin pull/3/head:new-pr 
          git merge --allow-unrelated-histories -s recursive -X theirs new-pr -m "merge"
          quarto render --to latex
          git add -f _book
          git commit -m "render new"
          OLD=$(git rev-parse HEAD~3)
          git-latexdiff --main _book/book-latex/testing.tex -o diff.pdf $OLD 
          
      - uses: actions/upload-artifact@v3
        with:
          name: Upload diff
          path: diff.pdf

